system:
  name: GAG_GG
  sequence: "ACE-GLY-ALA-GLY-NME"
  residue_to_delete: 3 

io:
  working_dir: 
  input_mdp_dir:
  output_dir: resdel_output
  output_prefix:
  log_file: 
  error_file:

prepare:
  GMX_executable:
  forcefield:
  water_model:

transform:
  molecule_name:
  number_of_lambdas: 15
  lambda_vector:
  vdw_lambda_vector:
  coul_lambda_vector:
  states:
    A:
      topology:
      structure:
      molecule_name:
    B:
      topology:
      structure:
      molecule_name:
