system:
  name: AAA_AA
  sequence: "ACE-ALA-ALA-ALA-NME"
  residue_to_delete: 2

io:
  working_dir: 
  input_mdp_dir:
  output_dir: resdel_output_2
  output_prefix:
  log_file: 
  error_file:

prepare:
  GMX_executable:
  forcefield:
  water_model:

transform:
  molecule_name:
  number_of_lambdas:  
  lambda_vector: [0.0, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 1.0]
  vdw_lambda_vector:
  coul_lambda_vector:
  states:
    A:
      topology:
      structure:
      molecule_name:
    B:
      topology:
      structure:
      molecule_name:
