[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "resdel"
version = "0.1.0"
description = "Tools for manipulating GROMACS topologies"
requires-python = ">=3.10"
dependencies = ["typer", "pyyaml"]

[project.scripts]
resdel="resdel.cli.main:app"

[tool.setuptools.packages.find]
where = ["src"]

